
package biletuygulamasi;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public  class JPanel_BiletKes extends javax.swing.JPanel {

    DosyaOkuYaz readwrite = new DosyaOkuYaz();
    static File otobusFile = new File("src/db/otobus.txt");
    
    private BufferedReader bufReader;
    private BufferedWriter bufWriter;
    private int secilenId;
    private String metin, secilenPlaka;
    
    
    public  JPanel_BiletKes() {
        initComponents();
        
    }
    private DefaultTableModel tabloAta()
    {
        DefaultTableModel tablo = new DefaultTableModel()
        { 
		public boolean isCellEditable(int row, int column)
		{  
	          return false;  
		}
	};
        
        tablo.addColumn("PLAKA");
        tablo.addColumn("KALKIŞ");
        tablo.addColumn("VARIŞ");
        tablo.addColumn("KALKIŞ SAAT");
        tablo.addColumn("VARIŞ SAAT");
        
        try
        {
            BufferedReader bufReader = readwrite.dosyaOku(otobusFile);
            String sCurrentLine;
            
            while ((sCurrentLine = bufReader.readLine()) != null) 
            {
                Vector vectorBilgiler=new Vector(5);
                String[] parcalar = sCurrentLine.split(" & ");
                vectorBilgiler.add(parcalar[0]); 
                vectorBilgiler.add(parcalar[1]); 
                vectorBilgiler.add(parcalar[2]);
                vectorBilgiler.add(parcalar[3]); 
                vectorBilgiler.add(parcalar[4]);
                
                tablo.addRow(vectorBilgiler);
            }
            bufReader.close();
        
        }catch(Exception Hata){}
        
        return tablo;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        Panel_BiletKes_OtobusBilgileri = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_OtobusListele = new javax.swing.JTable();
        jButton_BiletHazirla = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_Geri = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Panel_BiletKes_KoltukBilgileri = new java.awt.Panel();
        jLabel_OtobusBilgisi = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jButton4 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setRequestFocusEnabled(false);

        jTable_OtobusListele.setModel(tabloAta());
        jTable_OtobusListele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_OtobusListeleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_OtobusListele);

        jButton_BiletHazirla.setText("Devam");
        jButton_BiletHazirla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BiletHazirlaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Burak BEYKURT 2013");

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("    burakbeykurt@gmail.com     ");

        jButton_Geri.setText("Geri");
        jButton_Geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GeriActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biletuygulamasi/images/ticket2.png"))); // NOI18N

        javax.swing.GroupLayout Panel_BiletKes_OtobusBilgileriLayout = new javax.swing.GroupLayout(Panel_BiletKes_OtobusBilgileri);
        Panel_BiletKes_OtobusBilgileri.setLayout(Panel_BiletKes_OtobusBilgileriLayout);
        Panel_BiletKes_OtobusBilgileriLayout.setHorizontalGroup(
            Panel_BiletKes_OtobusBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_BiletKes_OtobusBilgileriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_BiletKes_OtobusBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_BiletKes_OtobusBilgileriLayout.createSequentialGroup()
                        .addComponent(jButton_Geri, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_BiletHazirla)))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_BiletKes_OtobusBilgileriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );
        Panel_BiletKes_OtobusBilgileriLayout.setVerticalGroup(
            Panel_BiletKes_OtobusBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BiletKes_OtobusBilgileriLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel_BiletKes_OtobusBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_BiletHazirla)
                    .addComponent(jButton_Geri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(Panel_BiletKes_OtobusBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)))
        );

        Panel_BiletKes_KoltukBilgileri.setPreferredSize(new java.awt.Dimension(589, 248));
        Panel_BiletKes_KoltukBilgileri.setVisible(false);

        jLabel_OtobusBilgisi.setFont(new java.awt.Font("Monotype Corsiva", 2, 14)); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        jButton4.setText("25");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_BiletKes_KoltukBilgileriLayout = new javax.swing.GroupLayout(Panel_BiletKes_KoltukBilgileri);
        Panel_BiletKes_KoltukBilgileri.setLayout(Panel_BiletKes_KoltukBilgileriLayout);
        Panel_BiletKes_KoltukBilgileriLayout.setHorizontalGroup(
            Panel_BiletKes_KoltukBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BiletKes_KoltukBilgileriLayout.createSequentialGroup()
                .addGroup(Panel_BiletKes_KoltukBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_BiletKes_KoltukBilgileriLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel_OtobusBilgisi, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_BiletKes_KoltukBilgileriLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(Panel_BiletKes_KoltukBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panel_BiletKes_KoltukBilgileriLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jButton4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_BiletKes_KoltukBilgileriLayout.setVerticalGroup(
            Panel_BiletKes_KoltukBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BiletKes_KoltukBilgileriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_OtobusBilgisi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(Panel_BiletKes_KoltukBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Panel_BiletKes_OtobusBilgileri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_BiletKes_OtobusBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_BiletKes_KoltukBilgileri, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_OtobusListeleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_OtobusListeleMouseClicked
       secilenId = jTable_OtobusListele.getSelectedRow();
       int i=0;
       try
        {
            BufferedReader bufReader = readwrite.dosyaOku(otobusFile);
            String sCurrentLine;
            
            while ((sCurrentLine = bufReader.readLine()) != null)
            {
                if(i==secilenId)
                {
                    String[] parcalar = sCurrentLine.split(" & ");
                    secilenPlaka = parcalar[0]; 
                    metin = "Plaka:"+parcalar[0]+"      Kalkış-Varış:"+parcalar[1]+"-"+parcalar[2]+"     Saat:"+parcalar[3]+"-"+parcalar[4];
                }
                i++;
            }
            
            bufReader.close();
            secilenId = -1;
            //JOptionPane.showMessageDialog(null, "SecilenPlaka "+secilenPlaka, "Başarılı", JOptionPane.PLAIN_MESSAGE);
                 
        }catch(Exception hata){}
    }//GEN-LAST:event_jTable_OtobusListeleMouseClicked

    private void jButton_BiletHazirlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BiletHazirlaActionPerformed
        //Panel_BiletKes_OtobusBilgileri.setVisible(false);
        //Panel_BiletKes_KoltukBilgileri.setVisible(true);
        //jLabel_OtobusBilgisi.setText(metin);
        JFrame_Otobus oto= new JFrame_Otobus();
        try 
        {
           oto.koltukDuzenle(secilenPlaka);
           oto.setTitle(secilenPlaka+" Plakalı Otobüsün Koltuk Durumu");
        } 
        catch (Exception ex) 
        {
           Logger.getLogger(JPanel_BiletKes.class.getName()).log(Level.SEVERE, null, ex);
        }
        oto.setVisible(true);
    }//GEN-LAST:event_jButton_BiletHazirlaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton_GeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GeriActionPerformed
        SetVisible.visibleAyarla(BiletUygulamasi.PanelMenu);
        
    }//GEN-LAST:event_jButton_GeriActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel Panel_BiletKes_KoltukBilgileri;
    private java.awt.Panel Panel_BiletKes_OtobusBilgileri;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_BiletHazirla;
    private javax.swing.JButton jButton_Geri;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_OtobusBilgisi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_OtobusListele;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
